### ISSUE TITLE
License terms?

### ISSUE THREAD

**Issue by janicez** [pflanze/better-qmail-remote#2]
There's no license shipped with this repository. All rights reserved?

**Comment by pflanze** [comment]
Let me know if there's still an issue.

**Comment by janicez** [comment]
There's not, thanks for clarifying.

On 26 September 2021 10:23:03 UTC, Christian Jaeger ***@***.***> wrote:
>Let me know if there's still an issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pflanze/better-qmail-remote/issues/2#issuecomment-927278621
-- 
Sent from my Android device, through postfix on invictus.wa.us.umbrellix.net, with K-9 Mail. Please excuse my brevity.
